"""empty message

Revision ID: 014c9c01722d
Revises: 2536f3b070c4
Create Date: 2025-06-13 09:50:54.265365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014c9c01722d'
down_revision = '2536f3b070c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
