"""empty message

Revision ID: 2536f3b070c4
Revises: 334b1a2deffb
Create Date: 2025-06-13 08:23:05.867160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2536f3b070c4'
down_revision = '334b1a2deffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('encrypted_content',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('encryption_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('encryption_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.alter_column('encrypted_content',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
