"""empty message

Revision ID: 274cc1b6f5cb
Revises: 4283087f6b79
Create Date: 2025-07-17 11:41:29.779191

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "274cc1b6f5cb"
down_revision = "4283087f6b79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notifications_enabled", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("chatbot_name", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("chatbot_name")
        batch_op.drop_column("notifications_enabled")

    # ### end Alembic commands ###
