"""empty message

Revision ID: 334b1a2deffb
Revises: bd21a02ae553
Create Date: 2025-06-12 13:25:05.951484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334b1a2deffb'
down_revision = 'bd21a02ae553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_content', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('content')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('encrypted_content')

    # ### end Alembic commands ###
