"""empty message

Revision ID: 4283087f6b79
Revises: e8881830d17b
Create Date: 2025-07-16 15:52:27.498428

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4283087f6b79"
down_revision = "e8881830d17b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tone", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("tone")

    # ### end Alembic commands ###
