"""empty message

Revision ID: 45de6b5f2dc4
Revises: d00737da230b
Create Date: 2025-07-14 14:13:38.977078

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45de6b5f2dc4"
down_revision = "d00737da230b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("weekly_summary_enabled", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("monthly_summary_enabled", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("monthly_summary_enabled")
        batch_op.drop_column("weekly_summary_enabled")

    # ### end Alembic commands ###
