"""empty message

Revision ID: 7386fd495707
Revises: 00de1daaee25
Create Date: 2025-07-21 10:18:56.530632

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7386fd495707"
down_revision = "00de1daaee25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_column("mood")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mood", sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
