"""empty message

Revision ID: 8e2d1607812e
Revises: 014c9c01722d
Create Date: 2025-06-13 10:34:45.614363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2d1607812e'
down_revision = '014c9c01722d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bookmarked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_column('is_bookmarked')

    # ### end Alembic commands ###
