"""empty message

Revision ID: 9fb1b0026ad1
Revises: e23f8e207075
Create Date: 2025-07-23 11:26:35.038145

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fb1b0026ad1"
down_revision = "e23f8e207075"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memory_images", schema=None) as batch_op:
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memory_images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_url", sa.VARCHAR(length=512), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
