"""empty message

Revision ID: a07049e07c08
Revises: b5d2347bfe66
Create Date: 2025-07-07 11:20:31.301545

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a07049e07c08"
down_revision = "b5d2347bfe66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prompts")
    # ### end Alembic commands ###
