"""empty message

Revision ID: b5b08f0120d4
Revises: 7386fd495707
Create Date: 2025-07-21 10:35:25.570987

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b5b08f0120d4"
down_revision = "7386fd495707"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_column("mood_value")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mood_value", sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
