"""empty message

Revision ID: d00737da230b
Revises: ef60d51fc603
Create Date: 2025-07-10 12:05:39.280589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00737da230b'
down_revision = 'ef60d51fc603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_memories_chat_id'), ['chat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_chat_id'))
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
