"""empty message

Revision ID: e8881830d17b
Revises: b49b498762d5
Create Date: 2025-07-16 13:15:09.808277

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8881830d17b"
down_revision = "b49b498762d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("memory_weight", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_column("memory_weight")

    # ### end Alembic commands ###
